#ifndef AD_TYPES_H
#define AD_TYPES_H

enum LaneAssociationType
{
    LANE_ASSOCIATION_TYPE_UNKNOWN,
    LANE_ASSOCIATION_TYPE_RIGHT,
    LANE_ASSOCIATION_TYPE_CENTER,
    LANE_ASSOCIATION_TYPE_LEFT
};

#endif

